[project]
name = "marketplace"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django==5.2.9",
    "python-dotenv>=1.2.1",
]

[dependency-groups]
dev = [
    "django-debug-toolbar>=6.1.0",
    "ruff>=0.14.9",
]
test = [
    "parameterized>=0.9.0",
]
