line-length = 79
exclude = ["migrations", "venv"]


[lint]
select = ["C4","N", "F", "W", "E", "I", "Q", "TID", "COM", "C4", "ERA", "RET", "PTH", "ISC", "C90", "T20", "SIM", "FIX", "INT", "DJ", "B"]


[format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"


[lint.isort]
force-sort-within-sections = true
known-first-party = ["lyceum", "about", "catalog", "core", "homepage"]


[lint.flake8-quotes]
inline-quotes = "single"


[lint.flake8-tidy-imports]
ban-relative-imports = "all"